apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgAKRPyKE7JkTjq/7CBHPW4Kb5t5osnvz5BQzjo135ORie7dZAcpe7w0RwtGrfsdu/qI7841dkFDyhL0b40Kwshvu4kOTmKo5DuUflIvGfFzfG1P8uU65gYosNXVeB8g7E87XvPAb6HIzOjt7ELnfleHiD4JKNxOyrfuTwkQY7jKDYB1JT0nVlmk+xJJ63BLoAmyG5Z9YtYbkAx2qQ9RkzerPW0+uKVDCzIMgjlR8PDuBcgYE/TgWM8zLOEMJzjzBqHLX+H+yhlhIE808Nfua7U0ot7HJp56MEkiQRVgV+yA29WrrR9Ab8ephHhkaeL8v1s3lkJIUXil6yQFS/Gd5mNDqM/sY6//eBl6QKq5Zpyj26qxQcaJ5gU4mcFTJOe1NrWOHZL80mKJf5TFE2eoYfLCeviYNK10H7kB/dCks/jzGwaJP+XibQ0a07hYk+CLavh0CxP4lwyWkccVYTZjl8j3x4++mmBWb/uHsFPmvHWl9jGLn5mxq9leV6hgCRpegohU516UZbUO3zimh7rgSARHFH8rCbZm7fk41MoZ4jNKJYkcRT0bPEzbOd1uZX+gdTcw62W+E1AgtC61SR85N83NfWmwhLjz761h8E9UQZD/5ka3VV1jpqjrkLVho6ibV3SoM/o2+uJfBt0Hq3iDmUmYxkYHn8DpNrW9Mgv4CgM2fzfqnP/W8Ar5+1EtQqn+57QMcjF550aihmizXjvRUHvPCyEs/vcrt0/vyPHeE31IsMY0lDZuQDLhKYrcenuBBkx3Bg/IeJ22Gg==
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale

